site_name: VeriGen
site_description: A general, config-driven Verilog/SystemVerilog code generator
site_author: GNPower
site_url: https://GNPower.github.io/VeriGen
repo_url: https://github.com/GNPower/VeriGen

copyright: "Copyright &copy; 2024 GNPower"

theme:
    name: material
    palette:
        - scheme: default
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode
        - scheme: slate
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
    icon:
        repo: fontawesome/brands/github
    features:
        - navigation.top
        - search.highlight
        - search.share

plugins:
    - search

markdown_extensions:
    - admonition
    - attr_list
    - def_list
    - pymdownx.superfences
    - pymdownx.highlight:
          linenums: true
    - toc:
          permalink: true

nav:
    - Home: index.md
    - Installation: installation.md
    - Authoring a Generator: authoring.md
    - Extension Hooks: extensions.md
    - Graphical Interface: gui.md
    - CLI Reference: cli.md
    - Report Issues: https://github.com/GNPower/VeriGen/issues
