// -----------------------------------------------------------------------------
// cdc_sync -- generated by VeriGen (Multi-bit Synchronizer v1.0.0)
// 8-bit, 3-stage synchronizer.
// -----------------------------------------------------------------------------
module cdc_sync #(
    parameter int WIDTH  = 8,
    parameter int STAGES = 3
) (
    input  logic             clk,
    input  logic             rst_n,
    input  logic [WIDTH-1:0] async_in,
    output logic [WIDTH-1:0] sync_out
);

    logic [WIDTH-1:0] sync_ff [STAGES];

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            for (int i = 0; i < STAGES; i++) begin
                sync_ff[i] <= {WIDTH{1'b0}};
            end
        end else begin
            sync_ff[0] <= async_in;
            for (int i = 1; i < STAGES; i++) begin
                sync_ff[i] <= sync_ff[i-1];
            end
        end
    end

    assign sync_out = sync_ff[STAGES-1];

endmodule
