// -----------------------------------------------------------------------------
// mux4 -- generated by VeriGen (N-to-1 Multiplexer v1.0.0)
// 4-input, 16-bit multiplexer.
// -----------------------------------------------------------------------------
module mux4 #(
    parameter int WIDTH = 16
) (
    input  logic [WIDTH-1:0] chan_a,
    input  logic [WIDTH-1:0] chan_b,
    input  logic [WIDTH-1:0] chan_c,
    input  logic [WIDTH-1:0] chan_d,
    input  logic [1:0] sel,
    output logic [WIDTH-1:0] y
);

    always_comb begin
        unique case (sel)
            2'd0: y = chan_a;
            2'd1: y = chan_b;
            2'd2: y = chan_c;
            2'd3: y = chan_d;
            default: y = '0;
        endcase
    end

endmodule
