// -----------------------------------------------------------------------------
// param_block -- generated by VeriGen (Parameter Types Demo v1.0.0)
// A demo module showing string, text, integer,
// float, choice, and boolean inputs.
// Target clock: 156.25 MHz | Implementation: dsp | Registered: True
// -----------------------------------------------------------------------------
module param_block #(
    parameter int WIDTH = 12
) (
    input  logic             clk,
    input  logic [WIDTH-1:0] d,
    output logic [WIDTH-1:0] q
);
    always_ff @(posedge clk) begin
        q <= d;
    end
endmodule
