// -----------------------------------------------------------------------------
// ring_buffer -- generated by VeriGen (Extension Hook Demo v1.0.0)
// DEPTH! 64 entries, 6-bit address.
// -----------------------------------------------------------------------------
module ring_buffer #(
    parameter int WIDTH      = 32,
    parameter int DEPTH      = 64,
    parameter int ADDR_WIDTH = 6
) (
    input  logic                  clk,
    input  logic                  we,
    input  logic [ADDR_WIDTH-1:0] waddr,
    input  logic [WIDTH-1:0]      wdata,
    input  logic [ADDR_WIDTH-1:0] raddr,
    output logic [WIDTH-1:0]      rdata
);

    logic [WIDTH-1:0] mem [DEPTH];

    always_ff @(posedge clk) begin
        if (we) begin
            mem[waddr] <= wdata;
        end
        rdata <= mem[raddr];
    end

endmodule
