"""``verigen`` command-line entry point.

Subcommands:
    generate   render a definition with a values config into an output directory
    validate   check a definition (and optionally a values config) without writing
    list       discover and list generator definitions (the catalog)
    new        scaffold a starter generator definition
    gui        launch the desktop wizard for a definition
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Dict, List, Optional

import yaml

from verigen import __version__
from verigen.core import catalog as catalog_mod
from verigen.core.errors import VeriGenError
from verigen.core.loader import load_definition
from verigen.core.pipeline import generate
from verigen.core.values import default_values, normalize_values


def _load_values(config_path: Optional[str]) -> Dict[str, Any]:
    if not config_path:
        return {}
    path = Path(config_path)
    if not path.is_file():
        raise VeriGenError(f"values config not found: {path}")
    try:
        data = yaml.safe_load(path.read_text(encoding="utf-8"))
    except yaml.YAMLError as exc:
        raise VeriGenError(f"could not parse values config {path}: {exc}") from exc
    if data is None:
        return {}
    if not isinstance(data, dict):
        raise VeriGenError("values config must be a mapping of variable to value")
    return data


def _cmd_generate(args: argparse.Namespace) -> int:
    definition = load_definition(args.definition)
    if args.config:
        values = _load_values(args.config)
    else:
        values = default_values(definition)
        print("No values config given (-c); using declared defaults.", file=sys.stderr)
    written = generate(
        definition,
        values,
        args.output,
        save_values=args.save_values,
    )
    print(f"Generated {len(written)} file(s) in '{args.output}':")
    for path in written:
        print(f"  {path}")
    return 0


def _cmd_validate(args: argparse.Namespace) -> int:
    definition = load_definition(args.definition)
    print(f"Definition OK: {definition.name} (id={definition.id})")
    if args.config:
        values = _load_values(args.config)
        normalize_values(definition, values)
        print(f"Values config OK: {args.config}")
    return 0


def _cmd_list(args: argparse.Namespace) -> int:
    if args.paths:
        paths = args.paths
        print(f"Generators found under: {', '.join(args.paths)}")
    else:
        paths = [str(catalog_mod.builtin_examples_dir())]
        print("Built-in example generators (pass a path to search elsewhere):")
    entries = catalog_mod.discover(paths)
    if not entries:
        print("No generator definitions found.")
        return 0
    for entry in entries:
        if entry.valid:
            print(f"[{entry.category}] {entry.id}: {entry.name}")
            if entry.description:
                print(f"    {entry.description}")
            print(f"    {entry.path}")
        else:
            print(f"[invalid] {entry.path}")
            print(f"    {entry.error}")
    return 0


_STARTER_DEFINITION = """\
verigen_version: "1"
id: {id}
name: {name}
description: A starter generator. Edit pages, outputs, and templates to taste.
version: "0.1.0"
category: General

pages:
  - title: Settings
    elements:
      - id: module_name
        type: string
        label: Module Name
        default: {id}
      - id: width
        type: integer
        label: Data Width
        default: 8
        min: 1
        max: 1024

outputs:
  - template: templates/module.sv.j2
    destination: "{{{{ module_name }}}}.sv"
"""

_STARTER_TEMPLATE = """\
// Generated by VeriGen ({{ verigen.name }} v{{ verigen.version }})
module {{ module_name }} #(
    parameter int WIDTH = {{ width }}
) (
    input  logic             clk,
    input  logic [WIDTH-1:0] d,
    output logic [WIDTH-1:0] q
);
    always_ff @(posedge clk) begin
        q <= d;
    end
endmodule
"""

_STARTER_VALUES = """\
module_name: my_module
width: 16
"""


def _cmd_new(args: argparse.Namespace) -> int:
    root = Path(args.output) / args.id
    if root.exists():
        raise VeriGenError(f"target already exists: {root}")
    (root / "templates").mkdir(parents=True)
    (root / "definition.yaml").write_text(
        _STARTER_DEFINITION.format(id=args.id, name=args.id.replace("_", " ").title()),
        encoding="utf-8",
    )
    (root / "templates" / "module.sv.j2").write_text(_STARTER_TEMPLATE, encoding="utf-8")
    (root / "values.example.yaml").write_text(_STARTER_VALUES, encoding="utf-8")
    print(f"Scaffolded a new generator at: {root}")
    print(f"  Try: verigen generate {root / 'definition.yaml'} -c {root / 'values.example.yaml'} -o out")
    return 0


def _cmd_schema(args: argparse.Namespace) -> int:
    import json

    from verigen.core.definition import GeneratorDefinition

    text = json.dumps(GeneratorDefinition.model_json_schema(), indent=2)
    if args.output:
        Path(args.output).write_text(text, encoding="utf-8")
        print(f"Wrote generator-definition JSON Schema to {args.output}")
    else:
        print(text)
    return 0


def _cmd_gui(args: argparse.Namespace) -> int:
    import importlib.util

    try:
        from verigen.ui.app import launch
    except ImportError as exc:
        raise VeriGenError(
            "the GUI requires the optional 'gui' extra: pip install verigen[gui]\n"
            f"({exc})"
        ) from exc
    native = not args.web
    if native and importlib.util.find_spec("webview") is None:
        print(
            "pywebview is not available; opening in the browser instead.", file=sys.stderr
        )
        native = False
    launch(definition=args.definition, native=native, port=args.port)
    return 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="verigen",
        description="A general, config-driven Verilog/SystemVerilog code generator.",
    )
    parser.add_argument("--version", action="version", version=f"%(prog)s {__version__}")
    sub = parser.add_subparsers(dest="command", required=True)

    p_gen = sub.add_parser("generate", help="render a definition into output files")
    p_gen.add_argument("definition", help="path to a generator-definition file")
    p_gen.add_argument("-c", "--config", help="path to a values config (YAML)")
    p_gen.add_argument("-o", "--output", required=True, help="output directory")
    p_gen.add_argument(
        "--save-values", action="store_true", help="also write the normalized values config"
    )
    p_gen.set_defaults(func=_cmd_generate)

    p_val = sub.add_parser("validate", help="validate a definition and/or values config")
    p_val.add_argument("definition", help="path to a generator-definition file")
    p_val.add_argument("-c", "--config", help="path to a values config (YAML)")
    p_val.set_defaults(func=_cmd_validate)

    p_list = sub.add_parser("list", help="discover and list generator definitions")
    p_list.add_argument(
        "paths",
        nargs="*",
        help="files or directories to search (default: the built-in examples)",
    )
    p_list.set_defaults(func=_cmd_list)

    p_new = sub.add_parser("new", help="scaffold a starter generator definition")
    p_new.add_argument("id", help="identifier for the new generator")
    p_new.add_argument("-o", "--output", default=".", help="parent directory (default: .)")
    p_new.set_defaults(func=_cmd_new)

    p_gui = sub.add_parser(
        "gui", help="launch the graphical interface (native window or browser)"
    )
    p_gui.add_argument(
        "definition", nargs="?", help="optional definition to open directly (else a catalog)"
    )
    p_gui.add_argument(
        "--web", action="store_true", help="open in the browser instead of a native window"
    )
    p_gui.add_argument("--port", type=int, default=8080, help="HTTP port (default: 8080)")
    p_gui.set_defaults(func=_cmd_gui)

    p_schema = sub.add_parser(
        "schema", help="print the generator-definition format as JSON Schema"
    )
    p_schema.add_argument("-o", "--output", help="write to this file instead of stdout")
    p_schema.set_defaults(func=_cmd_schema)

    return parser


def main(argv: Optional[List[str]] = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        return args.func(args)
    except VeriGenError as exc:
        print(f"\nError: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    sys.exit(main())
